# Predicting Employees Attrition

In this activity, you will apply your knowledge of deep learning models to predict whether an employee is likely to depart from a company.

## Instructions:

The steps for this activity are broken out into the following sections:

* Preprocess the data.

* Create a neural network model to predict employee attrition.

* Train and evaluate the neural network model.


#### Preprocess the Data 

1. Read the `HR-Employee-Attrition.csv` file from the Resources folder and create a DataFrame.

2. Review the resulting DataFrame. Check the data type associated with each column to identify categorical and non-categorical variables.

> **Hint** Recall that categorical variables have an `object` data type.

3. Create a list of categorical variables.

> **Rewind** The Pandas DataFrame `dtypes` property returns a Pandas Series that displays the data type of each column. The column name is the index. You can create the list of categorical variables manually. Or, you can use Pandas filtering. For more detail about the filtering process, review the [`dtypes` documentation at Pandas API reference](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dtypes.html).

4. Use the `OneHotEncoder` module from scikit-learn to encode the data set's categorical variables.

5. Create a new DataFrame named `attrition_df` that contains the encoded categorical variables and the numerical variables from the original dataset.

> **Note** To complete this step, you will employ the Pandas `concat()` function, which was introduced earlier in the course. Recall that we use the `concat` function to combine data from different DataFrames into a new DataFrame. In this case, you’ll use `concat` to create a new DataFrame containing the preprocessed data. You can learn more about the `concat` function in [this section of the Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html).

6. Use `attrition_df` to create the features (`X`) and target (`y`) sets. 

    * In this activity, we want to build a model that predicts whether a person is at risk for attrition. So, we must separate the attrition columns from the rest of the input data. In fact, because the attrition data is binary (one of two values), we only need to keep the “Attrition_Yes” column. We can ignore the “Attrition_No” column, because it is redundant. So, the “Attrition_Yes” column will become the target set `y`.

    * The rest of the DataFrame columns will become the features set `X`. 
    
7. Create the training and testing sets using the `train_test_split` function from scikit-learn.

8. Use scikit-learn’s `StandardScaler` to standardize the numerical features.

#### Create a Neural Network Model to Predict Employee Attrition

1. Use the optimization techniques presented in this lesson to create a deep neural network model with two hidden layers.

    * Set a variable `number_input_features` equal to the number of input features.

    * Set a variable `hidden_nodes_layer1` equal to an integer number close to the mean of the number of input features and the number of neurons in the output layer.

    * Set a variable `hidden_nodes_layer2` equal to an integer number close to the mean of the number of hidden nodes defined for the first layer and the number of neurons in the output layer.

    * Add the model’s layers, and use the `relu` activation function for each hidden layer.

    * This model will predict a binary output. So, add an output layer with one neuron, and use the `sigmoid` activation function.

> **Hint** To set the number of input features, you can fetch the length of the first element, like this: `number_input_features = len(X_train.iloc[0])`.

2. Display the structure of your model using the `summary` function.

3. Compile the model. Use the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` metric.


#### Train and Evaluate the Neural Network Model

1. Train (fit) the neural network model. Use the training data and set 100 epochs.

2. Evaluate the model using the test data to determine its loss and accuracy.


## References:

[Keras Sequential model](https://keras.io/api/models/sequential/)

[Keras Dense module](https://keras.io/api/layers/core_layers/dense/)

[Keras evaluate](https://keras.io/api/models/model_training_apis/)

[SKLearn OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)

In [1]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

---

## Preprocess the data.

### Step 1: Read the `HR-Employee-Attrition.csv` file from the Resources folder and create a DataFrame.

In [2]:
# Read the HR-Employee-Attrition.csv file from the Resources folder into a Pandas DataFrame
employee_df = pd.read_csv(
    Path("../Resources/HR-Employee-Attrition.csv")
)

### Step 2: Review the resulting DataFrame. Check the data type associated with each column to identify categorical and non-categorical variables.

> **Hint** Recall that categorical variables have an `object` data type.

In [3]:
# Review the DataFrame
employee_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [4]:
# Review the data types associated with the columns
employee_df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

### Step 3: Create a list of categorical variables.

In [5]:
# Create a list of categorical variables 
categorical_variables = list(employee_df.dtypes[employee_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

### Step 4: Use the `OneHotEncoder` module from scikit-learn to encode the data set's categorical variables.

In [6]:
# Imports
from sklearn.preprocessing import OneHotEncoder

In [7]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse_output=False)

# Encode categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(employee_df[categorical_variables])

In [8]:
# Create a DataFrame with the encoded variables
# The column names should match those of the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Display the DataFrame
encoded_df.head()

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

### Step 5: Create a new DataFrame named `attrition_df` that contains the encoded categorical variables and the numerical variables from the original dataset.

In [9]:
# Create a DataFrame with the columnns containing numerical variables from the original dataset
numerical_variables_df = employee_df.drop(columns = categorical_variables)

# Review the DataFrame
numerical_variables_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2,1,1,2,94,3,2,...,1,80,0,8,0,1,6,4,0,5
1,49,279,8,1,1,2,3,61,2,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1373,2,2,1,4,4,92,2,1,...,2,80,0,7,3,3,0,0,0,0
3,33,1392,3,4,1,5,4,56,3,1,...,3,80,0,8,3,3,8,7,3,0
4,27,591,2,1,1,7,1,40,3,1,...,4,80,1,6,3,3,2,2,2,2

In [10]:
# Using the Pandas concat function, combine the DataFrames the contain the encoded categorical data and the numerical data
attition_df = pd.concat(
    [
        numerical_variables_df,
        encoded_df
    ],
    axis=1
)

# Reveiw the DataFrame
attition_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

### Step 6: Use `attrition_df` to create the features (`X`) and target (`y`) sets. 

* In this activity, we want to build a model that predicts whether a person is at risk for attrition. So, we must separate the attrition columns from the rest of the input data. In fact, because the attrition data is binary (one of two values), we only need to keep the “Attrition_Yes” column. We can ignore the “Attrition_No” column, because it is redundant. So, the “Attrition_Yes” column will become the target set `y`.

* The rest of the DataFrame columns will become the features set `X`.

In [11]:
# Define the target set y using the Attrition_Yes column
y = attition_df["Attrition_Yes"]

# Display a sample of y
y[:5]

0    1.0
1    0.0
2    1.0
3    0.0
4    0.0
Name: Attrition_Yes, dtype: float64

In [12]:
# Define features set X by selecting all columns but Attrition_Yes and Attrition_No
X = attition_df.drop(columns=["Attrition_Yes", "Attrition_No"])

# Review the features DataFrame
X.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

### Step 7: Create the training and testing sets using the `train_test_split` function from scikit-learn.

In [13]:
# Split the data into training and testing datasets
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 8: Use scikit-learn’s `StandardScaler` to standardize the numerical features.

In [14]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Create a Neural Network Model to Predict Employee Attrition

### Step 1: Use the optimization techniques presented in this lesson to create a deep neural network model with two hidden layers.

* Set a variable `number_input_features` equal to the number of input features.

* Set a variable `hidden_nodes_layer1` equal to an integer number close to the mean of the number of input features and the number of neurons in the output layer.

* Set a variable `hidden_nodes_layer2` equal to an integer number close to the mean of the number of hidden nodes defined for the first layer and the number of neurons in the output layer.

* Add the model’s layers, and use the `relu` activation function for each hidden layer.

* This model will predict a binary output. So, add an output layer with one neuron, and use the `sigmoid` activation function.

> **Hint** To set the number of input features, you can fetch the length of the first element, like this: `number_input_features = len(X_train.iloc[0])`.

In [15]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Define the number of hidden nodes for the first hidden layer
# Use the mean of the number of input features plus the number of output nurons
# Use the Python floor division (//) to return the quotent
hidden_nodes_layer1 =  (number_input_features + 1) // 2 

# Define the number of hidden nodes for the second hidden layer
# Use the mean of the number of hidden nodes in the first hidden layer plus the number of output nurons
# Use the Python floor division (//) to return the quotent
hidden_nodes_layer2 = (hidden_nodes_layer1 + 1) // 2

# Create the Sequential model instance
nn = Sequential()

# Add the first hidden layer specifying the number of inputs, the number of hidden nodes, and the activation function
nn.add(tf.keras.Input(shape=(number_input_features,)))
nn.add(Dense(units=hidden_nodes_layer1, activation="relu"))

# Add the second hidden layer specifying the number of hidden nodes and the activation function
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

### Step 2: Display the structure of your model using the `summary` function.

In [16]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 28)             │         1,568 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 14)             │           406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,989 (7.77 KB)

 Trainable params: 1,989 (7.77 KB)

 Non-trainable params: 0 (0.00 B)

### Step 3: Compile the model. Use the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` metric.

In [17]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

---

## Train and Evaluate the Neural Network Model

### Step 1: Train (fit) the neural network model. Use the training data and set 100 epochs.

In [18]:
# Fit the model using 100 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.8379 - loss: 0.5150
Epoch 2/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.8514 - loss: 0.4085
Epoch 3/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.8390 - loss: 0.3952
Epoch 4/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - accuracy: 0.8547 - loss: 0.3471
Epoch 5/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 741us/step - accuracy: 0.8632 - loss: 0.3200
Epoch 6/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - accuracy: 0.8606 - loss: 0.3459
Epoch 7/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 765us/step - accuracy: 0.8704 - loss: 0.3220
Epoch 8/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - accuracy: 0.8797 - loss: 0.2982
Epoch 9/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - accuracy: 0.8967 - loss: 0.2885
Epoch 10/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - accuracy: 0.8994 - loss: 0.2642
Epoch 11/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.9107 - loss: 0.2583
Epoch 12/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.9165 - loss: 0.2610
Epoch 13/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.9161 - loss: 0.2366
Epoch 14/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.9215 - loss: 0.2390
Epoch 15/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - accuracy: 0.9137 - loss: 0.2439
Epoch 16/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.9236 - loss: 0.2359
Epoch 17/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.9358 - loss: 0.2074
Epoch 18/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9242 - loss: 0.2013
Epoch 19/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.9412 - loss: 0.1885
Epoch 20/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.9466 - loss: 0.1800
Epoch 21/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.9371 - loss: 0.1964
Epoch 22/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - accuracy: 0.9389 - loss: 0.2028
Epoch 23/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - accuracy: 0.9458 - loss: 0.1736
Epoch 24/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.9480 - loss: 0.1681
Epoch 25/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.9413 - loss: 0.1779
Epoch 26/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.9482 - loss: 0.1689
Epoch 27/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.9440 - loss: 0.1540
Epoch 28/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.9540 - loss: 0.1509
Epoch 29/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.9530 - loss: 0.1381
Epoch 30/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.9597 - loss: 0.1351
Epoch 31/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.9646 - loss: 0.1237
Epoch 32/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.9695 - loss: 0.1182
Epoch 33/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.9637 - loss: 0.1220
Epoch 34/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - accuracy: 0.9660 - loss: 0.1133
Epoch 35/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.9692 - loss: 0.1215
Epoch 36/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.9695 - loss: 0.1161
Epoch 37/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.9758 - loss: 0.0999
Epoch 38/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.9736 - loss: 0.0999
Epoch 39/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.9661 - loss: 0.1084
Epoch 40/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.9778 - loss: 0.0972
Epoch 41/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.9836 - loss: 0.0824
Epoch 42/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.9745 - loss: 0.0850
Epoch 43/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.9874 - loss: 0.0653
Epoch 44/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.9822 - loss: 0.0740
Epoch 45/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.9844 - loss: 0.0675
Epoch 46/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.9817 - loss: 0.0762
Epoch 47/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.9882 - loss: 0.0636
Epoch 48/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.9896 - loss: 0.0623
Epoch 49/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - accuracy: 0.9862 - loss: 0.0632
Epoch 50/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.9871 - loss: 0.0613
Epoch 51/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - accuracy: 0.9843 - loss: 0.0632
Epoch 52/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - accuracy: 0.9884 - loss: 0.0537
Epoch 53/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.9949 - loss: 0.0439
Epoch 54/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - accuracy: 0.9961 - loss: 0.0422
Epoch 55/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step - accuracy: 0.9953 - loss: 0.0380
Epoch 56/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - accuracy: 0.9940 - loss: 0.0402
Epoch 57/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.9871 - loss: 0.0486
Epoch 58/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.9929 - loss: 0.0335
Epoch 59/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - accuracy: 0.9969 - loss: 0.0329
Epoch 60/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.9933 - loss: 0.0328
Epoch 61/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step - accuracy: 0.9898 - loss: 0.0353
Epoch 62/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 0.9944 - loss: 0.0342
Epoch 63/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.9949 - loss: 0.0273
Epoch 64/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - accuracy: 0.9971 - loss: 0.0247
Epoch 65/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step - accuracy: 0.9965 - loss: 0.0234
Epoch 66/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - accuracy: 0.9960 - loss: 0.0271
Epoch 67/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 763us/step - accuracy: 0.9966 - loss: 0.0209
Epoch 68/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 0.9994 - loss: 0.0193
Epoch 69/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step - accuracy: 0.9958 - loss: 0.0219
Epoch 70/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - accuracy: 0.9966 - loss: 0.0221
Epoch 71/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 748us/step - accuracy: 0.9996 - loss: 0.0168
Epoch 72/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step - accuracy: 0.9963 - loss: 0.0193
Epoch 73/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - accuracy: 0.9952 - loss: 0.0227
Epoch 74/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - accuracy: 0.9996 - loss: 0.0141
Epoch 75/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 0.9987 - loss: 0.0164
Epoch 76/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step - accuracy: 0.9980 - loss: 0.0126
Epoch 77/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - accuracy: 0.9990 - loss: 0.0126
Epoch 78/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.9991 - loss: 0.0113
Epoch 79/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.9983 - loss: 0.0116
Epoch 80/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.9982 - loss: 0.0125
Epoch 81/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step - accuracy: 0.9971 - loss: 0.0117
Epoch 82/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.9962 - loss: 0.0117
Epoch 83/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - accuracy: 0.9978 - loss: 0.0092
Epoch 84/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 0.9990 - loss: 0.0094
Epoch 85/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - accuracy: 0.9999 - loss: 0.0095
Epoch 86/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.9999 - loss: 0.0075
Epoch 87/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 771us/step - accuracy: 1.0000 - loss: 0.0079
Epoch 88/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - accuracy: 1.0000 - loss: 0.0075
Epoch 89/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 1.0000 - loss: 0.0067
Epoch 90/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - accuracy: 1.0000 - loss: 0.0072
Epoch 91/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 1.0000 - loss: 0.0061
Epoch 92/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - accuracy: 1.0000 - loss: 0.0065
Epoch 93/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 1.0000 - loss: 0.0048
Epoch 94/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 1.0000 - loss: 0.0048
Epoch 95/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 783us/step - accuracy: 1.0000 - loss: 0.0052
Epoch 96/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 1.0000 - loss: 0.0048
Epoch 97/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 1.0000 - loss: 0.0046
Epoch 98/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step - accuracy: 1.0000 - loss: 0.0044
Epoch 99/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - accuracy: 1.0000 - loss: 0.0041
Epoch 100/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 774us/step - accuracy: 1.0000 - loss: 0.0039

### Step 2: Evaluate the model using the test data to determine its loss and accuracy.

In [19]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - 8ms/step - accuracy: 0.8234 - loss: 1.1006
Loss: 1.1005947589874268, Accuracy: 0.823369562625885

In [20]:
# Get the raw probability predictions from the model
y_pred_probabilities = nn.predict(X_test_scaled)

# Convert probabilities to binary class labels using a 0.5 threshold
# This line creates a boolean array (True/False) and then converts it to integers (1/0)
y_pred_binary = (y_pred_probabilities > 0.5).astype("int32")

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [21]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_binary))

              precision    recall  f1-score   support

         0.0       0.87      0.92      0.89       300
         1.0       0.53      0.41      0.46        68

    accuracy                           0.82       368
   macro avg       0.70      0.66      0.68       368
weighted avg       0.81      0.82      0.81       368